### ISSUE TITLE
ACE interaction suggestion

### ISSUE THREAD

**Issue by TacD21** [mgkid3310/AWESome#11]
Is it possible to put the Caution Voice (B****ing Betties) selection settings into the Addon setting instead of an interaction menu? to save time and space?

**Comment by mgkid3310** [comment]
In my case, I use f16 mode for combat and b747 for T/O and landing, so changing modes in addon setting every time would be a waste of time for pilots like me who frequently change GPWS mode. Instead, what about having a option for 'default' gpws setting? That could work for pilots who don't want to set GPWS mode every time they get into a plane.

**Comment by mgkid3310** [comment]
I'll close this thread on the weekend if there's no other suggestions
