### ISSUE TITLE
ATIS broadcast

### ISSUE THREAD

**Issue by TacD21** [mgkid3310/AWESome#3]
The ATIS is broadcasting across all vehicles with one person activating it and going across ground vehicles as well https://www.youtube.com/watch?v=wmraP1ccd10&feature=youtu.be&t=2245

**Comment by mgkid3310** [comment]
error fixed & hotfix update will be in <10min
thanks for reporting, I've made a silly mistake.

**Comment by TacD21** [comment]
Thanks for the quick response but now I can't seem to access anything using the ACE3 interaction

**Comment by mgkid3310** [comment]
all known bugs are fixed in v0.8.8 update
