### ISSUE TITLE
Conflict with C-130J from RHS

### ISSUE THREAD

**Issue by Dratam** [mgkid3310/AWESome#30]
**Describe the bug**
when you use the C-130J from RHS and the awsome Mod together the C-130 isent able to take off. on the runway it reaches 250+ kmh but
after liftoff you imediatly stall and lose power.
when you controll a AI via zeus everything is normal

**To Reproduce**
1. place C-130J from RHS
2. Start the Aircraft
3. Stall

**Expected behavior**
Iwould expect to be able to accelerate past 180 kmh in the air

**Screenshots**

**Game Environment:**
 - Additional Addons: [RHS,]
 - Date [e.g. 2019.06.1.]
 - cant find it but most recend steam version on 6.1.2019

**Additional context**
If you delete the airodynamics pbo it also works again so there seems to be a problem with the way it calculates this on the C-130J.

**Comment by mgkid3310** [comment]
In my environment I don't get the report. Can you check me a few thing to find the reason?

1. At what speed do you rotate(bring the nose up)?
2. Did you load any other addons than CBA, AWESome and RHS?
3. Was the plane empty or have cargo in it?

**Comment by Dratam** [comment]
well i looked into it again and deleated RHS and downloded it aigain now it worked.
seems like my clan was using an outdated version of RHS which somhow caused the bug.
and thanks for replying so quikly.

**Comment by mgkid3310** [comment]
Always look for updates lol
Thanks for your contribution ;)
