### ISSUE TITLE
Display speed in KIAS for aircraft

### ISSUE THREAD

**Issue by synixebrett** [mgkid3310/AWESome#47]
The checklists use KIAS right now for their speed but the game displays speed in km/h. AWESome should have the game display speed in KIAS when in aircraft.

**Comment by mgkid3310** [comment]
Trying to find where I can config vehicle status UI, but having no luck yet. Might take some time.

**Comment by synixebrett** [comment]
I originally was going to solve this for AWESome, but ACE wants it. Opened a PR there.

https://github.com/acemod/ACE3/pull/7046

**Comment by mgkid3310** [comment]
Oh ok, I've just looked up the PR but ctr looks too complicated for me :(

Would it be ok to close this issue?
