### ISSUE TITLE
ATIS Information + TFAR/ACRE compatibility

### ISSUE THREAD

**Issue by IzKhalifa** [mgkid3310/AWESome#59]
Most ATIS broadcasts end with an Information "Tag" to associate what time the information was received. My request is if you could add a way to make the ATIS broadcast start and end with an information tag, for example, ATIS BROADCAST STARTS, "This is information (ALPHA)... End information (ALPHA)." This would allow pilots to fully simulate proper radio reports at startup giving them updated weather information based on the received broadcast (Example, "information Alpha, information Juliet, information Mike ect."). You can code this into the automatic ATIS broadcasts by simply connecting the hour of the day during the multiplayer server or single player mission to the NATO phonetic alphabet up to X-Ray (since there is only 24 hours in a day).

Another request is to make it so that the ATIS broadcasts indefinitely on a set frequency if using TFAR radio or ACRE radio through teamspeak. Allow the ability to set ATIS to a certain frequency within TFAR/ACRE framework so that if you were using an Air Vehicle and you use the radio within the vehicle, you can switch to the ATIS frequency. This would be really cool to see implemented if you could as I don't know how to code this :D.

Here is an example of ATIS broadcast in DCS. 
https://www.youtube.com/watch?time_continue=36&v=ZTVZXxA0Wfc&feature=emb_title

The only thing I want to figure out would be how to add in the beginning and end of the ATIS broadcast "This is information (phonetic letter)" and "End information (phonetic letter)" and make it update based on hour of day. If you could help me figure out how to code this that would be sick!

Thank you! Also, the AWESome mod is awesome!

**Comment by mgkid3310** [comment]
I doubt if transmitting sound via TS3 would be viable, however playing ATIS when set to certain frequency could work. Phonetic designator is now on progress, however due to my RL ossues I'm not certain when the feature will be updated.

**Comment by IzKhalifa** [comment]
Thanks, that's awesome about the frequency thing! Phonetic designator will
be amazing im sure! No worries about time constraints, you're doing great!
have a good day.

**Comment by mgkid3310** [comment]
Information phonetic code is up in live version, but listening via ACRE/TFAR is not possible as far as i've tried. I'll close the issue here, thanks for your contribution.
