### ISSUE TITLE
Feature Request: Add Multilingual Support

### ISSUE THREAD

**Issue by GoldJohnKing** [mgkid3310/AWESome#60]
**Describe the solution you'd like**
Use stringtable.xml to have multilingual support.

**Comment by mgkid3310** [comment]
WIP, but takes too much time for me to replace all that text with stringtable. It will take quite time to be done.

**Comment by mgkid3310** [comment]
Stringtable updated with latest commit on main branch, can you check if everything you wanted are there on stringtable?

**Comment by GoldJohnKing** [comment]
> Stringtable updated with latest commit on main branch, can you check if everything you wanted are there on stringtable?

Seems good, I'll do the translate when I have time. 👍

**Comment by mgkid3310** [comment]
Sure, create a PR when done :)
