### ISSUE TITLE
AWESome GPWS bug

### ISSUE THREAD

**Issue by necroticism31** [mgkid3310/AWESome#61]
When i test my Bitching Betty she says all the functions, but when i fly and fight she says nothing of those. The only warning from her is pull up pull up all the time..... altitude is missing and sometimes she says about flares. I must use something else except AWESome with ACE? or the version 1.3.9 is broken? I saw many videos on youtube and Betty worked good, but this videos was all old

https://user-images.githubusercontent.com/79119890/108005494-8a26aa00-7001-11eb-89f3-b00b1ccb4b5e.mp4

**Comment by mgkid3310** [comment]
Theoretically the AWESome should work even only with the CBA. ACE provides additional features, but it's not necessary. The bug related to altitude warning is fixed and will be updated in a few days. Other than that, I couldn't find bugs in code nor my own test. Can you let me know the list of mods you used with?

**Comment by necroticism31** [comment]
Yes is working also without ace in every jet if you set it from the addons option. I test it much more better today  and seems like only the  altitude warning was the problem. I use mostly the F-16 Fighting Falcon mod, and some other plane mods like USAF Fighters, Boeing 737 etc... everything was fine. just that warning was missing. keep doing the great work, the AWESome mod is really awesome and im waiting for the fix so i can enjoy it way better. Thanks you :)

**Comment by mgkid3310** [comment]
Bug has been fixed in v3.1.10, thanks for your report :)
