### ISSUE TITLE
Feature Request: Pilot Set Callsign

### ISSUE THREAD

**Issue by Ellislee1** [mgkid3310/AWESome#62]
We run missions where pilots switch between aircraft regularly but keep the same callsign. Is there a way for a pilot to set their aircrafts callsign when seated in an aircraft? If not a method to allow pilots to set their own callsign outside of the init file would be useful.

**Comment by mgkid3310** [comment]
Would having a textbox in CBA addon settings work? I'm not familiar with Arma 3 GUI development, so I can't think of other place to put a input box.

**Comment by Ellislee1** [comment]
It may, if it was unique to each pilot/user that entered an aircraft. Apologies my Arma addon development knowladge is very poor.

**Comment by mgkid3310** [comment]
Updated on v1.3.11 and was uploaded
