### ISSUE TITLE
ATC Personel

### ISSUE THREAD

**Issue by Ellislee1** [mgkid3310/AWESome#63]
Apologies again for asking for ATC related stuff. 
Is there a way to assign an individual as ATC to view the ATC radar or can it only be done from the object with the initilization?

**Comment by mgkid3310** [comment]
It can be done, but requires some coding. Would adding an option to increase the ATC radar viewing range work? That way once the ATC spawns in and activates the radar, he will be able to see the radar regardless how far he is from the radar until he resapwns.

**Comment by Ellislee1** [comment]
> 
> 
> It can be done, but requires some coding. Would adding an option to increase the ATC radar viewing range work? That way once the ATC spawns in and activates the radar, he will be able to see the radar regardless how far he is from the radar until he resapwns.

Yeah, this would work assuming the palyer would be able to make the distance trivially large. Wouls this go in the objects initilization? e.g. `[this, _radarMode, _distance] call orbis_atc_fnc_addRadarScreen;`?

**Comment by mgkid3310** [comment]
Yes, if the `_distance` is not given the radar will have default distance, and if the `_distance` goes negative, i can make the distance infinite.

**Comment by Ellislee1** [comment]
That sounds perfect!

**Comment by mgkid3310** [comment]
Feature updated on v1.3.12, uploaded to Steam Workshop
