### ISSUE TITLE
Error popup in current workshop publish edition

### ISSUE THREAD

**Issue by GoldJohnKing** [mgkid3310/AWESome#65]
**Describe the bug**
When game launches, an error pops up. These are retrived from rpt file.
I've tried to compile the latest github code, the error still exists.

```
 1:17:00 Error in expression <pend ([_list, _indexes + [_i]] call FUNC(combinatnionProduct));
};

_products
} >
 1:17:00   Error position: <(combinatnionProduct));
};

_products
} >
 1:17:00   Error missing )
 1:17:00 File z\orbis\addons\main\functions\fnc_combinationProduct.sqf..., line 7
 1:17:00 Error in expression <pend ([_list, _indexes + [_i]] call FUNC(combinatnionProduct));
};

_products
} >
 1:17:00   Error position: <(combinatnionProduct));
};

_products
} >
 1:17:00   Error missing )
 1:17:00 File z\orbis\addons\main\functions\fnc_combinationProduct.sqf..., line 7
 1:17:00 Error in expression <itude + ((_randomVector select _i) ^ 2)
_offsetVector pushBack ((_coord select _>
 1:17:00   Error position: <_offsetVector pushBack ((_coord select _>
 1:17:00   Error missing ;
 1:17:00 File z\orbis\addons\main\functions\fnc_perlinNoise.sqf..., line 21
 1:17:00 Error in expression <itude + ((_randomVector select _i) ^ 2)
_offsetVector pushBack ((_coord select _>
 1:17:00   Error position: <_offsetVector pushBack ((_coord select _>
 1:17:00   Error missing ;
 1:17:00 File z\orbis\addons\main\functions\fnc_perlinNoise.sqf..., line 21
```

**To Reproduce**
1. Load the addon and launch the game, check rpt file.

**Expected behavior**
No error shows up

**Game Environment:**
 - ACE3, RHS
 - Date: 2021-06-22
 - (If available) Addon Version: current steam workshop version

**Comment by mgkid3310** [comment]
The fnc_perlinNoise.sqf and fnc_combinationProduct.sqf does nothing at this point. It was intended to be used in gust simulation, but is replaced by fnc_perlinNoise1D.sqf and is planned to be used at a later time. Therefore compiling error message may popup but will not have any effect in in-game experience. I'll have the compiling disabled in next release to remove the error message.

**Comment by mgkid3310** [comment]
What branch do you used for Arma 3? In my test environment just launching Arma 3 didn't spit compile error message.

**Comment by GoldJohnKing** [comment]
> What branch do you used for Arma 3? In my test environment just launching Arma 3 didn't spit compile error message.

I'm using stable branch, current version 2.04.147719.

The error message just flash then override by the main menu, it's not always noticeable. You can check in rpt file.

**Comment by mgkid3310** [comment]
Update code has been published, please comment or create a new issue when this issue happens again.
